# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  backendchallengeapi:
    image: backendchallengeapi
    build:
      context: .
      dockerfile: src/BackendChallenge.API/Dockerfile
    ports:
      - 5193:5193
